// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TelegramBot.AzFunc.RssReader.Data.Migrations
{
    [DbContext(typeof(ChannelDbContext))]
    partial class ChannelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TelegramBot.AzFunc.RssReader.Data.Entities.ChannelItemIdentity", b =>
                {
                    b.Property<string>("ItemLink")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ItemLink");

                    b.ToTable("ChannelItems");
                });
#pragma warning restore 612, 618
        }
    }
}
