// <auto-generated />
using HabrTelegramBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabrTelegramBot.Data.Migrations
{
    [DbContext(typeof(ChannelDbContext))]
    [Migration("20211228141938_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HabrTelegramBot.Data.Entities.ChannelItemIdentity", b =>
                {
                    b.Property<string>("ItemLink")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ItemLink");

                    b.ToTable("ChannelItems");
                });
#pragma warning restore 612, 618
        }
    }
}
